apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: test-app21-hpa
  labels:
    app: test-app21
    version: 0.0.1
    backstage.io/kubernetes-id: test-app21
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: test-app21
 minReplicas: 1
 maxReplicas: 4
 targetCPUUtilizationPercentage: 75